//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeEncuentro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class puntoencuentroEntities : DbContext
    {
        public puntoencuentroEntities()
            : base("name=puntoencuentroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_categorias> tb_categorias { get; set; }
        public DbSet<tb_lugar_voto> tb_lugar_voto { get; set; }
        public DbSet<tbcatlugar> tbcatlugar { get; set; }
        public DbSet<tbevento> tbevento { get; set; }
        public DbSet<tbgaleria> tbgaleria { get; set; }
        public DbSet<tbhorario> tbhorario { get; set; }
        public DbSet<tblugares> tblugares { get; set; }
        public DbSet<tbpago> tbpago { get; set; }
        public DbSet<tbpagolugares> tbpagolugares { get; set; }
        public DbSet<tbpersona> tbpersona { get; set; }
        public DbSet<tbtelefonos> tbtelefonos { get; set; }
        public DbSet<tbusuario> tbusuario { get; set; }
        public DbSet<tbvotousuario> tbvotousuario { get; set; }
        public DbSet<votos> votos { get; set; }
    }
}
