//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeEncuentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblugares
    {
        public tblugares()
        {
            this.tb_lugar_voto = new HashSet<tb_lugar_voto>();
            this.tbcatlugar = new HashSet<tbcatlugar>();
            this.tbevento = new HashSet<tbevento>();
            this.tbgaleria = new HashSet<tbgaleria>();
            this.tbhorario = new HashSet<tbhorario>();
            this.tbpagolugares = new HashSet<tbpagolugares>();
            this.tbtelefonos = new HashSet<tbtelefonos>();
            this.tbvotousuario = new HashSet<tbvotousuario>();
        }
    
        public int idlugar { get; set; }
        public string titulo { get; set; }
        public string direccion { get; set; }
        public string descripcion { get; set; }
        public string web { get; set; }
        public Nullable<int> imagen { get; set; }
        public string email { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> @long { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<tb_lugar_voto> tb_lugar_voto { get; set; }
        public virtual ICollection<tbcatlugar> tbcatlugar { get; set; }
        public virtual ICollection<tbevento> tbevento { get; set; }
        public virtual ICollection<tbgaleria> tbgaleria { get; set; }
        public virtual ICollection<tbhorario> tbhorario { get; set; }
        public virtual ICollection<tbpagolugares> tbpagolugares { get; set; }
        public virtual ICollection<tbtelefonos> tbtelefonos { get; set; }
        public virtual ICollection<tbvotousuario> tbvotousuario { get; set; }
    }
}
