//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeEncuentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbtelefonos
    {
        public int idtelefonos { get; set; }
        public Nullable<long> numero { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<int> codigoarea { get; set; }
        public Nullable<int> idlugares { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual tblugares tblugares { get; set; }
    }
}
