//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntoDeEncuentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbusuario
    {
        public tbusuario()
        {
            this.tbvotousuario = new HashSet<tbvotousuario>();
        }
    
        public long idusuario { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public string fid { get; set; }
        public string femail { get; set; }
        public string fullname { get; set; }
        public Nullable<decimal> gid { get; set; }
        public string gemail { get; set; }
        public System.DateTime creado { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechamodificacion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual tbpersona tbpersona { get; set; }
        public virtual ICollection<tbvotousuario> tbvotousuario { get; set; }
    }
}
